set expandtab
set tabstop=8
set softtabstop=4
set shiftwidth=4
set autoindent
syntax on
autocmd BufWritePre * :%s/\s\+$//e
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
colorscheme desert
au FocusLost * :wa
set autowriteall
set nu

au BufWinEnter * let w:m1=matchadd('Search', '\%>79v.\+', -1)

highlight ExtraWhitespace ctermbg=gray guibg=#592929
au ColorScheme * highlight ExtraWhitespace guibg=#592929
au BufEnter * match ExtraWhitespace /\s\+$/
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhiteSpace /\s\+$/


