" Copy to ~/.gvimrc or ~/_gvimrc.

"set guifont=Monaco:h12           " Font family and font size.
if has("gui_gtk2")
    set guifont=monofur\ 14
elseif has("gui_macvim")
    " set guifont=monofur:h17
    set guifont=Monaco:h13
end

set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set go-=r                         " Hide all the scollbars
set go-=R
set go-=l
set go-=L
set go-=m                         " Hide menu bar
set background=dark               " Background.
set lines=35 columns=100          " Window dimensions.


let g:solarized_termcolors=256

" colorscheme twilight
set background=light
colorscheme solarized

" better autocompletion menu colors
highlight Pmenu guibg=#646464
highlight Pmenu guifg=#dedede
highlight PmenuSel guibg=#592929

