" Copy or symlink to ~/.vimrc or ~/_vimrc.

set nocompatible                  " Must come first because it changes other options.

call pathogen#infect()

syntax enable                     " Turn on syntax highlighting.
filetype plugin on                " Turn on file type detection.
filetype indent on

set shell=sh

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.
set nofoldenable                  " disable folding

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

" set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory^=$HOME/.vim/tmp//   " Keep swap files in one location

set expandtab                    " Use spaces instead of tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smarttab
set autoread                       " auto reload file when it changes

" specific tab size for coffee, js and html
au FileType coffee setl sw=2 ts=2 sts=2 et
au FileType javascript setl sw=2 ts=2 sts=2 et
au FileType html setl sw=2 ts=2 sts=2 et
au FileType htmldjango setl sw=2 ts=2 sts=2 et
au FileType ruby setl sw=2 ts=2 sts=2 et
au FileType eruby setl sw=2 ts=2 sts=2 et

" toggle search highlight
nnoremap <F3> :set hls!<CR>

" highlight current line
" set cursorline

" ident/unindent with tabs on visual mode
vmap >  >gv
vmap <  <gv

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
" set statusline=[%n]\ %<%.99f\ %h%w%m%r%y%{fugitive#statusline()}\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

" colorscheme vividchalk
colorscheme desert

" Tab mappings.
map <C-Left> :tabprev<CR>
map <C-Right> :tabnext<CR>
map <C-t> :tabnew<CR>:tabmove<CR>
if has("unix")
      let s:uname = system("uname")
        if s:uname == "Darwin\n"
                map <D-Left> :tabprev<CR>
                map <D-Right> :tabnext<CR>
                map <D-t> :tabnext<CR>:tabmove<CR>
        endif
endif

" navigation through panels
nmap <silent> <S-Up> :wincmd k<CR>
nmap <silent> <S-Down> :wincmd j<CR>
nmap <silent> <S-Left> :wincmd h<CR>
nmap <silent> <S-Right> :wincmd l<CR>

" move panels to other position
map <leader>w<Left> <C-w>H
map <leader>w<Right> <C-w>L
map <leader>w<Up>  <C-w>K
map <leader>w<Down> <C-w>J

" open new split pane
map <leader>ws <ESC>:sp<CR>
map <leader>wv <ESC>:vs<CR>

" automatic trailing whitespace triming
autocmd BufWritePre * :%s/\s\+$//e

" Save on focus lost
au FocusLost * :wa
set autowriteall

" highlights lines over 80 columns
highlight LineOverWidth guibg=#424242 ctermbg=DarkGray
au ColorScheme * highlight LineOverWidth guibg=#424242
au BufWinEnter * let w:m1=matchadd('LineOverWidth', '\%>79v.\+', -1)

" highlists trailing whitespaces
highlight ExtraWhitespace ctermbg=gray guibg=#592929
au ColorScheme * highlight ExtraWhitespace guibg=#592929
au BufEnter * match ExtraWhitespace /\s\+$/
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhiteSpace /\s\+$/

" ignore system and auto generated stuff
set wildignore+=*/tmp/*,*.so,*.swp,*.swo,*.zip,*.pyc  " MacOSX/Linux
let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'

" paste and copy from clipboard
" set clipboard=unnamed
set clipboard=unnamedplus

" better autocompletion menu colors
highlight Pmenu ctermbg=LightGray guibg=#646464
highlight PmenuSel ctermbg=DarkBlue guibg=#592929

" tcomment plugin remap
map <leader>c :TComment<CR>
imap <leader>c <ESC>:TComment<CR>i

" convenient mappings
nnoremap <C-o> o<ESC>
nmap <space> i <ESC>


" syntastic settings
let g:syntastic_ruby_checkers = ['mri', 'rubocop']
let g:syntastic_python_checker = 'flake8'
let g:syntastic_python_checker_args = "--ignore=W391,W404,E123,E124,E126,E127,E128,F403"
let g:syntastic_javascript_checker = 'jshint'

nmap <leader>s :SyntasticCheck<CR>
imap <leader>s <ESC>:SyntasticCheck<CR>i

" NERDTree mapping
nnoremap <leader>t :NERDTreeToggle<CR>
let NERDTreeIgnore = ['\.pyc$']

" Yankstack
nmap <leader>p <Plug>yankstack_substitute_older_paste
nmap <leader>P <Plug>yankstack_substitute_newer_paste
call yankstack#setup()

" Indentline
let g:indentLine_enabled = 0
let g:indentLine_char = '┆'
nmap <leader>i :IndentLinesToggle<CR>
