const REMOVED = 'activities-config-button-removed';
const NEW_ICO = 'activities-config-button-icon-path';
const ORI_TXT = 'original-activities-button-text';
const NEW_TXT = 'activities-config-button-text';
const HOTC_TO = 'activities-config-hot-corner-delay';
const NO_HOTC = 'activities-config-hot-corner';
const NO_ICON = 'activities-config-button-no-icon';
const NO_TEXT = 'activities-config-button-no-text';
const PAD_TXT = 'activities-text-padding';
const PAD_ICO = 'activities-icon-padding';
const TRS_PAN = 'transparent-panel';
const CON_DET = 'enable-conflict-detection';
const COLOURS = 'panel-background-color-hex-rgb';
const HIDE_RC = 'panel-hide-rounded-corners';
const ICON_FILE = '/face-smile-3.svg'; // From Tango Project - Public Domain
