" Copy to ~/.gvimrc or ~/_gvimrc.

"set guifont=Monaco:h12           " Font family and font size.
if has("gui_gtk2")
    set guifont=Monaco\ 11
elseif has("gui_macvim")
    set guifont=Monaco:h12
end

set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set guioptions-=r                 " Hide rigth hand scollbar
set guioptions-=m                 " Hide menu bar
" set background=light            " Background.
set lines=35 columns=100          " Window dimensions.

" colorscheme vividchalk
colorscheme desert
highlight Pmenu guibg=#646464
highlight PmenuSel guibg=#592929

