#####################################################################
# CUSTOM SECTION
#

alias l='ls -F'
alias ll='ls -lah'


export PATH=$HOME/bin:$PATH

# Custom bash prompt via kirsle.net/wizards/ps1.html
export PS1="\[$(tput bold)\]\[$(tput setaf 5)\][\[$(tput setaf 2)\]\u\[$(tput setaf 5)\] :: \[$(tput setaf 2)\]\w\[$(tput setaf 5)\]] \[$(tput setaf 4)\]\$(vcprompt)\[$(tput setaf 1)\]\n>> \[$(tput sgr0)\]"

# Add RVM to PATH for scripting
# PATH=$PATH:$HOME/.rvm/bin
